name: Pipline

on:
  push:
      tags:
        - "v*"

jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: poetry install --with dev
      - name: Build wheel
        run: poetry build --format wheel
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          run: poetry build --format wheel
          files: |
            **/*.whl

  test:
    name: Pull and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: poetry install --with dev
      - name: Test package
        run: poetry run tox